### ISSUE TITLE
Failure to load

### ISSUE THREAD

**Issue by menagerie198** [Chrstn67/WonderBox#1]
I keep getting a 'failed to load plugin 'wonderbox' when I try to enable it.

**Comment by Chrstn67** [comment]
Hello. Thanks for trying the plugin. I will check this as soon as possible... Can you send me screenshots of the version you have, and of the obsidian developer console, please ?

**Comment by menagerie198** [comment]
Sure... 
Obsidian 1.8.0
Installer 1.7.7
Wonderbox 1.0.6
![image](https://github.com/user-attachments/assets/94091d8f-6660-4417-8b1f-4181f5c23a76)

**Comment by Flexit07** [comment]
Same problem for me
Obsidian 1.7.7
Installer 1.7.4
Wonderbox 1.0.6

**Comment by Chrstn67** [comment]
Ok... Thanks....

**Comment by edward-peters** [comment]
Same for me

**Comment by menagerie198** [comment]
Version 1.0.9 loaded, and enabled OK! Thanks.
Unfortunately the 'wonderboxes' are not rendering for me.

**Comment by menagerie198** [comment]
Boom! 1.0.15 is working!!

**Comment by Chrstn67** [comment]
🎉
Great, the next step for me will be to have a box within a box system...

Thank you all for your feedback, I am closing the issue.

**Comment by Flexit07** [comment]
working like a charm now, thanks!

**Comment by Flexit07** [comment]
I'm sorry to write that I've just discovered another bug. 

Wonderbox, once activated, prevents you from expanding and compressing the "callout" native plugin and the similar "Admonition" plugin by the Community.

I already tested the problem many times and I can confirm that, once Wonderbox is disabled, those callouts works normally
